### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [gtm-templates-simo-ahava/audienceproject-userreport#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text argument and return a URI Encoded string. You should use this method on "data.iabConsent" and "data.iabConsentString" when generating the url
const scriptUrl = 'https://sak.userreport.com/' +encodeUriComponent(data.publisherId) +'/launcher.js' +(data.iabConsent ? '?iab_consent=' + data.iabConsentString : '');

**Comment by sahava** [comment]
Thanks - this is fixed in https://github.com/gtm-templates-simo-ahava/audienceproject-userreport/commit/94f0d0ac259287584e4907b439cc8833fbcdb79d - only `data.iabConsentString` needed to be encoded, as `data.iabConsent` is just a boolean check.

Should I resubmit the template or will you take it from here? I've updated metadata.yaml with the correct commit hash.

**Comment by delsonting** [comment]
We'll re-review, no need to resubmit.
